In [8]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.model_selection import train_test_split
from scipy import stats


df=pd.read_csv(r'C:\Users\Dhruv stark\Desktop\machine learning practice\Advertising.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   radio       200 non-null    float64
 3   newspaper   200 non-null    float64
 4   sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [27]:
df.sum().isnull()

Unnamed: 0    False
TV            False
radio         False
newspaper     False
sales         False
dtype: bool

In [28]:
df.describe().T

            count      mean        std  min     25%     50%      75%    max
Unnamed: 0  200.0  100.5000  57.879185  1.0  50.750  100.50  150.250  200.0
TV          200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
radio       200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
newspaper   200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
sales       200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

In [29]:
# there is unnamed columm to drop unnammed column if present

In [33]:
if 'Unnamed: 0' in df.columns: 
    df.drop('Unnamed: 0',axis=1,inplace= True)
df.columns = {c.strip() if c in columns }
rename_map = {c.strip() if c.upper() 

df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9